apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-service-qa
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://35.224.24.120   # AKS cluster
  sources:
    - path: inventory-app-chart
      repoURL: https://github.com/ramanujds/gitops-repo-multi-cluster
      targetRevision: HEAD
      helm:
        releaseName: inventory-service
        valueFiles:
          - $values/environments/qa/values/inventory-values.yaml
    - repoURL: https://github.com/ramanujds/gitops-repo-multi-cluster
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true