apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-order-app-dev
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc   # Local Docker Desktop cluster
  source:
    path: environments/dev/apps
    repoURL: https://github.com/ramanujds/gitops-repo-multi-cluster
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true